#!/usr/bin/env python3
"""
Neuronix Interactive Setup Script
Helps users configure API keys and select their preferred LLM provider.
"""

import os
import sys
from pathlib import Path


def print_header():
    print("""
╔════════════════════════════════════════════════════════════╗
║           🧠 NEURONIX SETUP - API KEY CONFIGURATION        ║
╚════════════════════════════════════════════════════════════╝
    """)


def print_providers():
    print("""
Available LLM Providers:

1. ⚡ GROQ (Recommended for testing)
   - Free tier, fast inference
   - No credit card required
   - Link: https://console.groq.com

2. 🤖 OpenAI (GPT-4, GPT-3.5)
   - Premium models
   - Requires paid account
   - Link: https://platform.openai.com/api-keys

3. 🎁 Google Gemini
   - Good performance, free tier available
   - Link: https://aistudio.google.com/app/apikey

4. 📚 View Full Setup Guide
   - Open SETUP_GUIDE.md for detailed instructions
    """)


def get_provider_choice() -> str:
    while True:
        choice = input("Select a provider (1-4): ").strip()
        
        if choice == "1":
            return "groq"
        elif choice == "2":
            return "openai"
        elif choice == "3":
            return "gemini"
        elif choice == "4":
            os.system("cat SETUP_GUIDE.md" if os.name != "nt" else "type SETUP_GUIDE.md")
            continue
        else:
            print("❌ Invalid choice. Please select 1-4.")
            continue


def configure_provider(provider: str) -> dict:
    """Get API key and configuration for the selected provider."""
    config = {"provider": provider}
    
    if provider == "groq":
        print("\n📖 Setting up GROQ")
        print("1. Visit: https://console.groq.com")
        print("2. Sign up (free)")
        print("3. Go to 'API Keys' section")
        print("4. Click 'Create API Key'")
        print("5. Copy the key below\n")
        
        api_key = input("Enter your GROQ API key: ").strip()
        if api_key:
            config["GROQ_API_KEY"] = api_key
            config["DEFAULT_LLM_PROVIDER"] = "groq"
        else:
            print("❌ No API key provided")
            return None
    
    elif provider == "openai":
        print("\n📖 Setting up OpenAI")
        print("1. Visit: https://platform.openai.com/api-keys")
        print("2. Sign up / Login")
        print("3. Click 'Create new secret key'")
        print("4. Copy the key below (shown only once!)\n")
        
        api_key = input("Enter your OpenAI API key (sk-...): ").strip()
        if api_key:
            config["OPENAI_API_KEY"] = api_key
            config["DEFAULT_LLM_PROVIDER"] = "openai"
            print("\n💳 Note: You'll need a paid account with usage credits")
            print("   Set billing limits at: https://platform.openai.com/account/billing/limits")
        else:
            print("❌ No API key provided")
            return None
    
    elif provider == "gemini":
        print("\n📖 Setting up Google Gemini")
        print("1. Visit: https://aistudio.google.com/app/apikey")
        print("2. Click 'Create API Key'")
        print("3. Copy the key below\n")
        
        api_key = input("Enter your Gemini API key: ").strip()
        if api_key:
            config["GEMINI_API_KEY"] = api_key
            config["DEFAULT_LLM_PROVIDER"] = "gemini"
        else:
            print("❌ No API key provided")
            return None
    
    return config


def write_env_file(config: dict):
    """Write configuration to .env file."""
    env_file = Path(".env")
    
    # Read existing .env if it exists
    existing_env = {}
    if env_file.exists():
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    existing_env[key] = value
    
    # Update with new config
    existing_env.update(config)
    
    # Write back to .env
    with open(env_file, "w") as f:
        f.write("# Neuronix Framework - Configuration\n")
        f.write("# Generated by setup script\n\n")
        
        # Write provider-specific keys
        for key in ["DEFAULT_LLM_PROVIDER", "GROQ_API_KEY", "OPENAI_API_KEY", 
                    "GEMINI_API_KEY"]:
            if key in existing_env and existing_env[key]:
                f.write(f"{key}={existing_env[key]}\n")
        
        f.write("\n# Other settings (optional)\n")
        for key, value in existing_env.items():
            if key not in ["DEFAULT_LLM_PROVIDER", "GROQ_API_KEY", "OPENAI_API_KEY",
                           "GEMINI_API_KEY"]:
                if value:
                    f.write(f"{key}={value}\n")
    
    print(f"✅ Configuration saved to .env")


def verify_setup():
    """Verify the setup by testing the LLM."""
    print("\n" + "="*60)
    response = input("Would you like to test the setup now? (y/n): ").strip().lower()
    
    if response != "y":
        print("\n✅ Setup complete!")
        print("📖 You can run: python test_run.py")
        print("🖥️  Or use the CLI: python -m neuronix.main query \"Your question\"")
        return
    
    print("\n🧪 Testing setup...")
    
    try:
        from neuronix.llm import get_llm
        from neuronix.config.settings import settings
        
        print(f"📦 Using provider: {settings.DEFAULT_LLM_PROVIDER}")
        
        llm = get_llm(settings.DEFAULT_LLM_PROVIDER)
        print("✅ LLM initialized successfully!")
        
        print("\n🤔 Generating a test response...\n")
        response = llm.generate("Say 'Hello from Neuronix!' in one sentence.")
        print(f"📝 Response: {response}\n")
        
        print("✅ Setup verified and working!")
        
    except Exception as e:
        print(f"❌ Error during test: {str(e)}")
        print("   Please check your API key and try again.")


def main():
    print_header()
    
    # Check if .env exists
    if Path(".env").exists():
        print("⚠️  .env file already exists")
        response = input("Do you want to reconfigure? (y/n): ").strip().lower()
        if response != "y":
            print("Skipping configuration.")
            verify_setup()
            return
    
    print_providers()
    provider = get_provider_choice()
    
    config = configure_provider(provider)
    if not config:
        print("❌ Configuration cancelled.")
        return
    
    write_env_file(config)
    
    print(f"\n✅ Configured {provider.upper()} as your default LLM provider")
    
    verify_setup()
    
    print("\n" + "="*60)
    print("📚 Next steps:")
    print("   1. Read SETUP_GUIDE.md for detailed information")
    print("   2. Run: python test_run.py")
    print("   3. Try the CLI: python -m neuronix.main query \"Your question\"")
    print("   4. Check out the documentation for advanced usage")
    print("="*60)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(0)
